// Seeded once on first visit so the board and dashboard are not empty.
export const SAMPLE_TASKS = [
  {
    id: 'sample-1',
    title: 'Write project proposal',
    description: 'Draft the scope and timeline for project 1.',
    category: 'General',
    startDate: '2026-08-20',
    dueDate: '2026-08-25',
    completeDate: '2026-08-23',
    personId: 'P01',
    status: 'DONE',
  },
  {
    id: 'sample-2',
    title: 'Design the board layout',
    description: 'Three columns: TO DO, DOING and DONE.',
    category: 'Design',
    startDate: '2026-08-26',
    dueDate: '2026-08-30',
    completeDate: '2026-08-30',
    personId: 'P02',
    status: 'DONE',
  },
  {
    id: 'sample-3',
    title: 'Implement local storage',
    description: 'Persist tasks and categories between refreshes.',
    category: 'Development',
    startDate: '2026-09-01',
    dueDate: '2026-09-04',
    completeDate: '2026-09-06',
    personId: 'P03',
    status: 'DONE',
  },
  {
    id: 'sample-4',
    title: 'Build the dashboard charts',
    description: 'Status, category and completion performance charts.',
    category: 'Development',
    startDate: '2026-09-02',
    dueDate: '2026-09-10',
    completeDate: '',
    personId: 'P04',
    status: 'DOING',
  },
  {
    id: 'sample-5',
    title: 'Test every task action',
    description: 'Create, edit, delete and move tasks.',
    category: 'Testing',
    startDate: '2026-09-05',
    dueDate: '2026-09-12',
    completeDate: '',
    personId: 'P05',
    status: 'TO DO',
  },
  {
    id: 'sample-6',
    title: 'Write the README',
    description: 'Description, screenshots and usage instructions.',
    category: 'General',
    startDate: '2026-08-28',
    dueDate: '2026-09-01',
    completeDate: '',
    personId: 'P01',
    status: 'TO DO',
  },
]
